### PR TITLE
Adds status of previously executed command in notification

### PR DESCRIPTION
**Pull request by athityakumar**
Handles issue #2

### CODE REVIEW

**Comment by kaustubhhiware** [comment]
This is really great @athityakumar !
Thanks :smile:

**Comment by athityakumar** [comment]
Wait, let me resolve the merge conflict 😄

**Comment by icyflame** [comment]
Hey @athityakumar , can you maybe change the icon from terminal to green / red depending on the success status? I remember there are icons in gtk for this.

**Comment by kaustubhhiware** [comment]
You can use the scripts mentioned in this [Stackoverflow answer](https://stackoverflow.com/questions/7539621/where-gtk-finds-icon-names-to-use-with-gtk-image-new-from-icon-name/7541503) to find which gtkicon looks appropriate.

**Comment by kaustubhhiware** [comment]
The icon for unsuccessful is only to be changed.
Following are the candidate icons: dialog-error, dialog-warning, emblem-important, emblem-unreadable, mail-mark-junk, process-stop.

Regardless of what icon you use, please mention all these are available in a comment.

**Comment by icyflame** [comment]
Success: face-smile, face-smile-big
Failure: face-angry, security-high

There are several icons! I wish they had image renders on that page instead of just descriptions

**Comment by kaustubhhiware** [comment]
@icyflame You can use an image. I was using an image for a long time, but that might seem a dependency for some people, so removed images and used default system icons. See [this](https://github.com/kaustubhhiware/NotiFyre/commit/dd11514484bf55856450740e0b3e4aff86e1b448#diff-f2e73e009bcaae5534d3638fbb66571dR16) commit.

**Comment by athityakumar** [comment]
Hmm, why not just ASCII icons of green tick (`\u2705` : ✅) and red cross (`\u274c` : ❌)?

**Comment by athityakumar** [comment]
For some reason, the above comments feel like this. 😉 

image

**Comment by kaustubhhiware** [comment]
The idea is to use an appropriate image according to the status, but the image shouldn't be too distracting.
You have full freedom to do whatever you want, so go right ahead.
But having a big green icon and a big red icon does not seem as the way to go.

**Comment by athityakumar** [comment]
@kaustubhhiware - As per our recent discussion, I've added ASCII tick and cross to the notification title. Have a look. 😄 

image

**Comment by kaustubhhiware** [comment]
Cool :smile: 

Now, the web interface says there are certain merge conflicts, make sure you rebase once.
Also, to keep commits atomic, please squash all commits into one.

I'll merge right after this.

**Comment by icyflame** [comment]
@athityakumar That UI looks dope! The present text thing was hard to read, this is much better! Thanks! :smile:

**Comment by athityakumar** [comment]
@kaustubhhiware - Merge conflict? No, I don't see any. And feel to merge by "Squash and commit". 😄 

image

@icyflame - Welcome! 😄

**Pull request merged**
